/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./components/404.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    ComingSoon: typeof import('./components/comingSoon.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Faas: typeof import('./components/faas.vue')['default']
    Footer: typeof import('./components/footer.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    List: typeof import('./components/faas/list.vue')['default']
    Main: typeof import('./components/treedb/main.vue')['default']
    MdViewer: typeof import('./components/docs/mdViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/setting.vue')['default']
  }
}
